// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var escape, log;
  log = function() {
    return console.log.apply(console, arguments);
  };
  exports.escape = escape = function(str) {
    return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\s/g, "<span class='space'>&nbsp;</span>");
  };
  exports.unescape = function(str) {
    var div;
    div = document.createElement("div");
    div.innerHTML = str;
    return div.innerText;
  };
  exports.input = function(input) {
    var end, p2, s1, s2, s3, start, text;
    log(input);
    text = input.value;
    start = input.selectionStart;
    end = input.selectionEnd;
    s1 = escape(text.slice(0, start));
    p2 = escape(text.slice(start, end));
    s2 = "<span class='selection'>" + p2 + "</span>";
    s3 = escape(text.slice(end));
    return "" + s1 + s2 + s3;
  };
  exports.tab = function(input, down) {
    var end, start, text;
    log(input);
    start = input.selectionStart;
    end = input.selectionEnd;
    text = input.value;
    input.value = text.slice(0, start) + " " + text.slice(end);
    input.selectionStart = start + 1;
    input.selectionEnd = start + 1;
    input.onkeyup();
    return down.returnValue = false;
  };
  return exports;
});
